[package]
name = "lava_torrent_cli"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
clap = { version = "3", features = ["derive"] }
expanded-pathbuf = "0.1"
lava_torrent = "0.8"
